### PR TITLE
added user - routes, model, controllers. update server.js

### PR DESCRIPTION
**Pull request by jimdavies72**
added user folder

added userRoutes.js
added userControllers.js
added userModel.js

updated server.js with userRouter.

### CODE REVIEW

**Review by clarkenewsh — COMMENTED** [review]
Nice work - all good from me!

**Comment by EethanF** [comment]
Looks good!

**Comment by CatTiac** [comment]
Yep same, good stuff!

**Review by EethanF — APPROVED** [review]
Looks good!

**Review by CatTiac — APPROVED** [review]
All looks good!

**Comment by ConnahShackley** [comment]
yeah got it thanks

**Review by ConnahShackley — COMMENTED** [review]
got it thanks

**Review by ConnahShackley — APPROVED** [review]
got it thanks

**Pull request merged**
